#!/usr/bin/env python3
from argparse import ArgumentParser
from pathlib import Path
from urllib.parse import quote
from xml.sax.saxutils import escape


def build_feed_urls(provider: str, identifier: str) -> tuple[str, str, str]:
    if provider == "gangan-online":
        return (
            f"http://manga-feeds.freshrss.svc.cluster.local:8080/gangan-online/{identifier}.xml",
            f"https://www.ganganonline.com/title/{identifier}",
            "Gangan ONLINE chapter feed generated by manga-feeds",
        )
    if provider == "yanmaga":
        slug = quote(identifier, safe="%")
        return (
            f"http://manga-feeds.freshrss.svc.cluster.local:8080/yanmaga/{slug}.xml",
            f"https://yanmaga.jp/comics/{slug}",
            "ヤンマガWeb episode feed generated by manga-feeds",
        )
    raise ValueError(f"unsupported provider: {provider}")


def build_opml(provider: str, identifier: str, feed_title: str, category: str) -> str:
    feed_url, html_url, description = build_feed_urls(provider, identifier)
    return "\n".join(
        [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<opml version="2.0">',
            "  <head>",
            "    <title>manga-feeds import</title>",
            "  </head>",
            "  <body>",
            f'    <outline text="{escape(category)}">',
            (
                f'      <outline text="{escape(feed_title)}" type="rss" '
                f'xmlUrl="{escape(feed_url)}" htmlUrl="{escape(html_url)}" '
                f'description="{escape(description)}" />'
            ),
            "    </outline>",
            "  </body>",
            "</opml>",
            "",
        ]
    )


def main() -> None:
    parser = ArgumentParser(description="Generate FreshRSS OPML for manga-feeds.")
    parser.add_argument(
        "--provider",
        choices=["gangan-online", "yanmaga"],
        default="gangan-online",
        help="manga-feeds provider route",
    )
    parser.add_argument("--title-id", help="Gangan ONLINE title ID; kept for backward compatibility")
    parser.add_argument("--slug", help="Provider slug, such as a URL-encoded yanmaga comics slug")
    parser.add_argument("--feed-title", required=True, help="FreshRSS feed title")
    parser.add_argument("--category", default="changedetection.io", help="FreshRSS category")
    parser.add_argument("--output", help="Output path; stdout when omitted")
    args = parser.parse_args()

    identifier = args.slug or args.title_id
    if not identifier:
        parser.error("--title-id or --slug is required")
    opml = build_opml(args.provider, identifier, args.feed_title, args.category)
    if args.output:
        Path(args.output).write_text(opml, encoding="utf-8")
    else:
        print(opml, end="")


if __name__ == "__main__":
    main()
