import { spawnSync } from 'node:child_process';
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  buildFeedUrls,
  buildOpml,
} from '../.apm/skills/manga-rss-bridge/scripts/generate_freshrss_opml.mts';

const root = resolve(import.meta.dirname, '..');
const scriptPath = '.apm/skills/manga-rss-bridge/scripts/generate_freshrss_opml.mts';
const script = join(root, scriptPath);
const run = (args: string[]) =>
  spawnSync(process.execPath, [script, ...args], { encoding: 'utf8' });
const pixivArgs = ['--provider', 'pixiv-comic', '--work-id', '8789', '--feed-title', '例'];

describe('FreshRSS OPML generator', () => {
  it('builds existing Gangan and Pixiv feed URLs without changing identifiers', () => {
    expect(buildFeedUrls('gangan-online', '2061')).toEqual([
      'http://manga-feeds.freshrss.svc.cluster.local:8080/gangan-online/2061.xml',
      'https://www.ganganonline.com/title/2061',
      'Gangan ONLINE chapter feed generated by manga-feeds',
    ]);
    expect(buildFeedUrls('pixiv-comic', '8789')).toEqual([
      'http://manga-feeds.freshrss.svc.cluster.local:8080/pixiv-comic/8789.xml',
      'https://comic.pixiv.net/works/8789',
      'Pixivコミック episode feed generated by manga-feeds',
    ]);
    expect(buildFeedUrls('pixiv-comic', '9007199254740993')[1]).toBe(
      'https://comic.pixiv.net/works/9007199254740993',
    );
    expect(() => buildFeedUrls('unsupported', '1')).toThrow('unsupported provider');
  });

  it('encodes raw YanMaga slugs while preserving percent-encoded ones', () => {
    const raw = "ねずみの初恋 /?&!'()*~";
    const encoded =
      '%E3%81%AD%E3%81%9A%E3%81%BF%E3%81%AE%E5%88%9D%E6%81%8B%20%2F%3F%26%21%27%28%29%2A~';
    const expected = [
      `http://manga-feeds.freshrss.svc.cluster.local:8080/yanmaga/${encoded}.xml`,
      `https://yanmaga.jp/comics/${encoded}`,
      'ヤンマガWeb episode feed generated by manga-feeds',
    ];
    expect(buildFeedUrls('yanmaga', raw)).toEqual(expected);
    expect(buildFeedUrls('yanmaga', encoded)).toEqual(expected);
  });

  it('rejects noncanonical Pixiv IDs', () => {
    for (const id of ['', '0', '0008789', '-1', '+1', '1.2', '1e3', '１２', '1\n', ' 1']) {
      expect(() => buildFeedUrls('pixiv-comic', id)).toThrow('positive decimal integer');
    }
  });

  it('escapes XML attributes, including quotes and whitespace', () => {
    const opml = buildOpml('gangan-online', '1?a=2&b=3', '漫画 "A" & <B>\n続き', "Comic's\tRSS\r");
    expect(opml).toBe(
      [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<opml version="2.0">',
        '  <head>',
        '    <title>manga-feeds import</title>',
        '  </head>',
        '  <body>',
        '    <outline text="Comic&apos;s&#9;RSS&#13;">',
        '      <outline text="漫画 &quot;A&quot; &amp; &lt;B&gt;&#10;続き" type="rss" xmlUrl="http://manga-feeds.freshrss.svc.cluster.local:8080/gangan-online/1?a=2&amp;b=3.xml" htmlUrl="https://www.ganganonline.com/title/1?a=2&amp;b=3" description="Gangan ONLINE chapter feed generated by manga-feeds" />',
        '    </outline>',
        '  </body>',
        '</opml>',
        '',
      ].join('\n'),
    );
  });

  it('defaults to the user manga category and keeps provider and identifier aliases', () => {
    const result = run(['--title-id', '2061', '--feed-title', '作品']);
    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toBe(buildOpml('gangan-online', '2061', '作品', 'Comic - Manga RSS'));
    const slugResult = run(['--title-id', '2061', '--slug', '999', '--feed-title', '作品']);
    expect(slugResult.status, slugResult.stderr).toBe(0);
    expect(slugResult.stdout).toBe(buildOpml('gangan-online', '999', '作品', 'Comic - Manga RSS'));
    const pixivResult = run(pixivArgs);
    expect(pixivResult.status, pixivResult.stderr).toBe(0);
    expect(pixivResult.stdout).toBe(buildOpml('pixiv-comic', '8789', '例', 'Comic - Manga RSS'));
  });

  it('honors an explicit category and UTF-8 output file without stdout', () => {
    const directory = mkdtempSync(join(tmpdir(), 'manga-opml-'));
    try {
      const output = join(directory, '漫画.opml');
      const result = run([...pixivArgs, '--category', 'changedetection.io', '--output', output]);
      expect(result.status, result.stderr).toBe(0);
      expect(result.stdout).toBe('');
      expect(result.stderr).toBe('');
      expect(readFileSync(output, 'utf8')).toBe(
        buildOpml('pixiv-comic', '8789', '例', 'changedetection.io'),
      );
      const failed = run([...pixivArgs, '--output', join(directory, 'missing', 'feed.opml')]);
      expect(failed.status).toBe(1);
      expect(failed.stdout).toBe('');
      expect(failed.stderr).toContain('error:');
      expect(failed.stderr).not.toContain('at main');
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });

  it('reports invalid arguments with exit 2 and no stack trace or partial output', () => {
    const cases: [string[], string][] = [
      [['--title-id', '2061'], '--feed-title is required'],
      [['--feed-title', '作品'], '--title-id or --slug is required'],
      [['--provider', 'pixiv-comic', '--feed-title', '作品'], '--work-id is required'],
      [['--work-id', '8789', '--feed-title', '作品'], '--work-id is only supported'],
      [[...pixivArgs, '--work-id', '0008789'], 'positive decimal integer'],
      [
        ['--provider', 'unknown', '--title-id', '1', '--feed-title', '作品'],
        'unsupported provider',
      ],
      [[...pixivArgs, '--unknown'], 'Unknown option'],
      [[...pixivArgs, '--output'], 'argument missing'],
      [[...pixivArgs, 'unexpected'], 'Unexpected argument'],
    ];
    for (const [args, message] of cases) {
      const result = run(args);
      expect(result.status, result.stderr).toBe(2);
      expect(result.stdout).toBe('');
      expect(result.stderr).toContain(message);
      expect(result.stderr).not.toContain('at main');
    }
  });

  it('shows help without requiring identifiers', () => {
    for (const flag of ['--help', '-h']) {
      const result = run([flag]);
      expect(result.status, result.stderr).toBe(0);
      expect(result.stdout).toContain('--work-id');
      expect(result.stdout).toContain('default: Comic - Manga RSS');
    }
  });

  it('runs a copied skill script without repository packages and keeps the deployed copy in sync', () => {
    expect(readFileSync(join(root, scriptPath.replace('.apm/', '.agents/')), 'utf8')).toBe(
      readFileSync(script, 'utf8'),
    );
    const directory = mkdtempSync(join(tmpdir(), 'manga-opml-standalone-'));
    try {
      const copiedScript = join(directory, 'generate_freshrss_opml.mts');
      copyFileSync(script, copiedScript);
      writeFileSync(join(directory, 'package.json'), JSON.stringify({ type: 'commonjs' }));
      const result = spawnSync(process.execPath, [copiedScript, ...pixivArgs], {
        cwd: directory,
        encoding: 'utf8',
      });
      expect(result.status, result.stderr).toBe(0);
      expect(result.stderr).toBe('');
      expect(result.stdout).toBe(buildOpml('pixiv-comic', '8789', '例', 'Comic - Manga RSS'));
    } finally {
      rmSync(directory, { recursive: true, force: true });
    }
  });
});
