import importlib.util
import subprocess
import sys
import unittest
from pathlib import Path
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / ".apm" / "skills" / "manga-rss-bridge" / "scripts" / "generate_freshrss_opml.py"
SPEC = importlib.util.spec_from_file_location("generate_freshrss_opml", SCRIPT)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("could not load OPML generator")
GENERATOR = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(GENERATOR)


class PixivComicOpmlTests(unittest.TestCase):
    def test_build_feed_urls_for_pixiv_comic(self) -> None:
        self.assertEqual(
            GENERATOR.build_feed_urls("pixiv-comic", "8789"),
            (
                "http://manga-feeds.freshrss.svc.cluster.local:8080/pixiv-comic/8789.xml",
                "https://comic.pixiv.net/works/8789",
                "Pixivコミック episode feed generated by manga-feeds",
            ),
        )

    def test_rejects_noncanonical_pixiv_comic_work_id(self) -> None:
        with self.assertRaisesRegex(ValueError, "positive decimal integer"):
            GENERATOR.build_feed_urls("pixiv-comic", "0008789")

    def test_cli_generates_pixiv_comic_opml_with_requested_category(self) -> None:
        result = subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--provider",
                "pixiv-comic",
                "--work-id",
                "8789",
                "--feed-title",
                "楠木さんは高校デビューに失敗している",
                "--category",
                "Comic - Manga RSS",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        root = ElementTree.fromstring(result.stdout)
        category = root.find("./body/outline")
        self.assertIsNotNone(category)
        self.assertEqual(category.attrib.get("text"), "Comic - Manga RSS")
        feed = category.find("./outline") if category is not None else None
        self.assertIsNotNone(feed)
        self.assertEqual(feed.attrib.get("text"), "楠木さんは高校デビューに失敗している")
        self.assertEqual(
            feed.attrib.get("xmlUrl"),
            "http://manga-feeds.freshrss.svc.cluster.local:8080/pixiv-comic/8789.xml",
        )
        self.assertEqual(feed.attrib.get("htmlUrl"), "https://comic.pixiv.net/works/8789")

    def test_cli_reports_invalid_work_id_without_traceback(self) -> None:
        result = subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--provider",
                "pixiv-comic",
                "--work-id",
                "0008789",
                "--feed-title",
                "例",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(result.returncode, 2)
        self.assertIn("Pixiv Comic work ID must be a positive decimal integer", result.stderr)
        self.assertNotIn("Traceback", result.stderr)


if __name__ == "__main__":
    unittest.main()
