#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
import { parseArgs } from 'node:util';

export const buildFeedUrls = (provider: string, identifier: string): [string, string, string] => {
  const baseUrl = 'http://manga-feeds.freshrss.svc.cluster.local:8080';
  switch (provider) {
    case 'gangan-online':
      return [
        `${baseUrl}/gangan-online/${identifier}.xml`,
        `https://www.ganganonline.com/title/${identifier}`,
        'Gangan ONLINE chapter feed generated by manga-feeds',
      ];
    case 'yanmaga': {
      // Match urllib.parse.quote(identifier, safe='%'): keep already encoded slugs.
      const slug = encodeURIComponent(identifier)
        .replaceAll('%25', '%')
        .replace(
          /[!'()*]/g,
          (character) => `%${character.charCodeAt(0).toString(16).toUpperCase()}`,
        );
      return [
        `${baseUrl}/yanmaga/${slug}.xml`,
        `https://yanmaga.jp/comics/${slug}`,
        'ヤンマガWeb episode feed generated by manga-feeds',
      ];
    }
    case 'pixiv-comic':
      if (!/^[1-9][0-9]*$/.test(identifier)) {
        throw new Error('Pixiv Comic work ID must be a positive decimal integer');
      }
      return [
        `${baseUrl}/pixiv-comic/${identifier}.xml`,
        `https://comic.pixiv.net/works/${identifier}`,
        'Pixivコミック episode feed generated by manga-feeds',
      ];
    default:
      throw new Error(`unsupported provider: ${provider}`);
  }
};

const escapeAttribute = (value: string): string =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
    .replaceAll('\t', '&#9;')
    .replaceAll('\n', '&#10;')
    .replaceAll('\r', '&#13;');

export const buildOpml = (
  provider: string,
  identifier: string,
  feedTitle: string,
  category: string,
): string => {
  const [feedUrl, htmlUrl, description] = buildFeedUrls(provider, identifier);
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<opml version="2.0">',
    '  <head>',
    '    <title>manga-feeds import</title>',
    '  </head>',
    '  <body>',
    `    <outline text="${escapeAttribute(category)}">`,
    `      <outline text="${escapeAttribute(feedTitle)}" type="rss" xmlUrl="${escapeAttribute(feedUrl)}" htmlUrl="${escapeAttribute(htmlUrl)}" description="${escapeAttribute(description)}" />`,
    '    </outline>',
    '  </body>',
    '</opml>',
    '',
  ].join('\n');
};

const help = `Generate FreshRSS OPML for manga-feeds.

Usage: node generate_freshrss_opml.mts [options]
  --provider <name>   gangan-online (default), yanmaga, or pixiv-comic
  --title-id <id>     Gangan ONLINE title ID; kept for backward compatibility
  --slug <slug>       Provider slug, including URL-encoded yanmaga comics slugs
  --work-id <id>      Pixiv Comic work ID
  --feed-title <text> FreshRSS feed title (required)
  --category <text>   FreshRSS category (default: Comic - Manga RSS)
  --output <path>     Output path; stdout when omitted
  -h, --help         Show this help
`;

const main = (): void => {
  let opml: string;
  let output: string | undefined;
  try {
    const { values } = parseArgs({
      options: {
        provider: { type: 'string', default: 'gangan-online' },
        'title-id': { type: 'string' },
        slug: { type: 'string' },
        'work-id': { type: 'string' },
        'feed-title': { type: 'string' },
        category: { type: 'string', default: 'Comic - Manga RSS' },
        output: { type: 'string' },
        help: { type: 'boolean', short: 'h' },
      },
      strict: true,
      allowPositionals: false,
    });
    if (values.help) {
      process.stdout.write(help);
      return;
    }
    if (values['feed-title'] === undefined) throw new Error('--feed-title is required');
    let identifier: string | undefined;
    if (values.provider === 'pixiv-comic') {
      identifier = values['work-id'];
      if (!identifier) throw new Error('--work-id is required for pixiv-comic');
    } else {
      if (values['work-id']) throw new Error('--work-id is only supported for pixiv-comic');
      identifier = values.slug || values['title-id'];
      if (!identifier) throw new Error('--title-id or --slug is required');
    }
    opml = buildOpml(values.provider, identifier, values['feed-title'], values.category);
    output = values.output;
  } catch (error) {
    console.error(`error: ${error instanceof Error ? error.message : String(error)}`);
    console.error('Use --help for usage.');
    process.exitCode = 2;
    return;
  }

  try {
    if (output) writeFileSync(output, opml, 'utf8');
    else process.stdout.write(opml);
  } catch (error) {
    console.error(`error: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
};

if (import.meta.main) main();
